SET NUMERIC_ROUNDABORT OFF
GO
SET XACT_ABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

BEGIN TRY
BEGIN TRANSACTION

-- AGGIUNTA DELLA NUOVA COLONNA

-- POPOLAMENTO NUOVA COLONNA

-- AGGIORNAMENTO STORED PROCEDURES

-- INSERIRE QUI GLI SCRIPT SQL GENERATI DAL TOOL

COMMIT TRANSACTION
PRINT 'Script concluso con successo'

END TRY
BEGIN CATCH
PRINT 'Rollback execution...'
SELECT ERROR_MESSAGE() AS ErrorMessage;
ROLLBACK
END CATCH